/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blog: typeof import('./src/components/Blog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Clients: typeof import('./src/components/Clients.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    HeroVideo: typeof import('./src/components/HeroVideo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    References: typeof import('./src/components/References.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
